<?php
ob_start();
include('MysqliDb.php');
include('General.php');
include ('tcpdf/tcpdf.php');
define('UPLOAD_PATH','../uploads');

$pathFront=realpath('../uploads');
$pdf = new TCPDF();
$pdf->AddPage();
$general=new Deforay_Commons_General();

$configQuery="SELECT * from global_config";
$configResult=$db->query($configQuery);
$arr = array();
// now we create an associative array so that we can easily create view variables
for ($i = 0; $i < sizeof($configResult); $i++) {
  $arr[$configResult[$i]['name']] = $configResult[$i]['value'];
}
        $html = '';
        $html.='<table style="padding:2px;width:100%;font-size:10px;font-family:Times New Roman;">';
            $html.='<tr>';
                $html.='<td style="font-size:15px;margin-top:-80px;width:60%;">Viral Load Laboratory Request From</td>';
                $html.='<td></td>';
                if(isset($arr['logo']) && trim($arr['logo'])!= '' && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo" . DIRECTORY_SEPARATOR . $arr['logo'])){
                  $html .='<td rowspan="2"><img src="../uploads/logo/'.$arr['logo'].'" style="width:50px;height:50px;float:right;" alt="logo"></td>';
                }else{
                  $html.='<td rowspan="2"></td>';
                }
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:35%;">Province ---------------------------------</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:35%;">District ---------------------------------</td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:35%;">Clinic name ---------------------------</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:50%;">Sample Collection date ----------/---------/-------</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:20%;">Time ------------</td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:35%;">Clinician name ---------------------------</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:45%;">First name --------------------------------------------</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:20%;">Surname -------------</td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:45%">Patient ART Number -----------------------------------</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:45%";>Current ART regimen -----------------------------</td>';
                $html.='<td></td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:35%;">Sex(tick one)<input type="checkbox" name="gender" value="male"/>Male&nbsp;<input type="checkbox" name="gender" value="female" />Female</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:40%;">Date Of ART initiation ----------/---------/-------</td>';
                $html.='<td></td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:30%;">DOB --------/--------/--------</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:35%;">If no DOB Age ------ years</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:35%;">If < 1 year Age ------ months</td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:50%;">Currently pregnant(tick one)<input type="checkbox" name="gender" value="yes"/>Yes&nbsp;<input type="checkbox" name="gender" value="no" />No</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:50%;">Currently breastfeeding(tick one)<input type="checkbox" name="gender" value="yes"/>Yes&nbsp;<input type="checkbox" name="gender" value="no" />No</td>';
                $html.='<td></td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:50%;">Date of last viral load tested  ---------/---------/---------</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:50%;">Result last viral load ------------- copies/ml</td>';
                $html.='<td></td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td colspan="3" style="line-height:25px;font-size:10px;font-weight:100;text-align:left;">Reason viral load requested(tick one)<input type="checkbox" name="request" value="routine"/>Routine &nbsp;<input type="checkbox" name="request" value="targetfail" />Target clinical failure&nbsp;<input type="checkbox" name="request" value="targetfail" />Targeted</td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td colspan="3" style="line-height:25px;font-size:10px;font-weight:100;text-align:left;"> immunological failure<input type="checkbox" name="request" value="repeat"/>Repeat After Enhanced Adherence &nbsp;Other ---------------------------------------</td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td colspan="3" style="line-height:25px;font-size:10px;font-weight:100;text-align:left;">If After Enhanced Adherence:Poor Adherence was identified <input type="checkbox" name="gender" value="yes"/>Yes&nbsp;<input type="checkbox" name="gender" value="no" />No</td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td colspan="3" style="line-height:25px;font-size:10px;font-weight:100;text-align:left;">Number of Enhanced Sessions &nbsp;<input type="checkbox" name="gender" value="1"/>1&nbsp;<input type="checkbox" name="gender" value="2" />2&nbsp;<input type="checkbox" name="gender" value="3"/>3&nbsp;<input type="checkbox" name="gender" value="4" />4</td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td colspan="3" style="font-size:13px;">FOR LABORATORY USE ONLY</td>';
            $html.='</tr><hr/>';
            $html.='<tr>';
                $html.='<td colspan="2" style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:75%;">VL Platform(tick one)<input type="checkbox" name="request" value="routine"/>BioMerieux &nbsp;<input type="checkbox" name="request" value="targetfail" />Roche &nbsp;<input type="checkbox" name="request" value="targetfail" />Abbott &nbsp;<input type="checkbox" name="request" value="poc" />POC</td>';
                $html.='<td></td>';
            $html.='</tr><hr style="width:75%;"/>';
            $html.='<tr>';
                $html.='<td colspan="2" style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:75%;">Test Method(tick one)<input type="checkbox" name="request" value="routine"/>Individual &nbsp;<input type="checkbox" name="request" value="targetfail" />Minipool &nbsp;<input type="checkbox" name="request" value="targetfail" />Other Pooling algorithm</td><td rowspan="3"></td>';
                $html.='<td></td>';
            $html.='</tr><hr style="width:75%;"/>';
            $html.='<tr>';
                $html.='<td colspan="3" style="line-height:25px;font-size:10px;font-weight:100;text-align:left;">Specimen Type(tick one)<input type="checkbox" name="request" value="routine"/>EDTA DBS &nbsp;<input type="checkbox" name="request" value="targetfail" />PP DBS &nbsp;<input type="checkbox" name="request" value="targetfail" />DBS &nbsp;<input type="checkbox" name="request" value="poc" />PLASMA &nbsp;<input type="checkbox" name="request" value="blood" />WHOLE BLOOD</td>';
            $html.='</tr><hr/>';
            $html.='<tr>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:33%;">Date of result  ---------/---------/---------</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:39%;">Viral Load result ----------------------- copies/ml</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:27%";>Approved by ------------------------</td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td colspan="2" style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:55%;">If no result ------------------------------------------------------------------</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:45%;">Date Received stamp  -------/-------/-------</td>';
            $html.='</tr><hr/>';
            $html.='<tr style="">';
                $html.='<td colspan="2" style="height:45px;line-height:25px;font-size:10px;font-weight:100;text-align:left;width:75%;">Laboratory Officer comments ------------------------------------------------------</td>';
                $html.='<td></td>';
            $html.='</tr>';
            $html.='<tr><td colspan="3" style="border-top-style:dotted;border-width:1px;width:100%;">tear here</td></tr>';
            $html.='<tr>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:50%;">Sample Collection date --------/-------/------ Time ----- ------ -----</td>';
                $html.='<td style="line-height:25px;font-size:10px;font-weight:100;text-align:left;width:50%;">Patient name and surname ------------------------</td>';
                $html.='<td></td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td colspan="2" style="line-height:25px;font-size:10px;font-weight:100;text-align:left;">Patient OI number ---------------------- &nbsp;&nbsp;Patient phone number --------------------------</td>';
                $html.='<td></td>';
            $html.='</tr>';
            $html.='<tr>';
                $html.='<td colspan="2" style="line-height:25px;font-size:10px;font-weight:100;text-align:left;">Viral Load result --------------- copies/ml &nbsp;&nbsp;Date VL received  -------/-------/-------</td>';
                $html.='<td></td>';
            $html.='</tr>';
        $html.='</table>';
$pdf->writeHTML($html);
$pdf->lastPage();
$filename = 'vl-zambia-form.pdf';
$pdf->Output($pathFront . DIRECTORY_SEPARATOR . $filename,"F");
echo $filename;
?>