<?php

// SYSTEM GENERATED FILE. DO NOT EDIT.

// THIS FILE IS USED TO GENERATE THE MENU TRANSLATION.

_("Dashboard");
_("Admin");
_("Access Control");
_("Roles");
_("Users");
_("Facilities");
_("Monitoring");
_("System Configuration");
_("Lab Tests Config");
_("VL Config");
_("EID Config");
_("Covid-19 Config");
_("Hepatitis Config");
_("TB Config");
_("User Activity Log");
_("Audit Trail");
_("API History");
_("Source of Requests");
_("General Configuration");
_("Instruments");
_("Geographical Divisions");
_("Implementation Partners");
_("Funding Sources");
_("Sample Types");
_("Testing Reasons");
_("Test Failure Reasons");
_("ART Regimen");
_("Symptoms");
_("Rejection Reasons");
_("Sample Rejection Reasons");
_("Sample Type");
_("Test Result Units");
_("Results");
_("Test Methods");
_("Test Reasons");
_("Test Categories");
_("Test Type Configuration");
_("Co-morbidities");
_("QC Test Kits");
_("Risk Factors");
_("LAB TESTS");
_("Request Management");
_("Test Result Management");
_("Management");
_("VIRAL LOAD");
_("EARLY INFANT DIAGNOSIS (EID)");
_("COVID-19");
_("Hepatitis");
_("TB");
_("View Test Requests");
_("Add New Request");
_("Add Samples from Manifest");
_("Manage Batch");
_("Specimen Manifest");
_("Enter Result Manually");
_("Failed/Hold Samples");
_("Manage Results Status");
_("Sample Status Report");
_("Export Results");
_("Print Result");
_("Sample Rejection Report");
_("Import Result From File");
_("Control Report");
_("Clinic Reports");
_("VL Lab Weekly Report");
_("Sample Monitoring Report");
_("VL Testing Target Report");
_("EID Specimen Manifest");
_("Clinic Report");
_("EID Testing Target Report");
_("Confirmation Manifest");
_("Record Confirmatory Tests");
_("Covid-19 QC Data");
_("COVID-19 Testing Target Report");
_("Hepatitis Specimen Manifest");
_("Hepatitis Testing Target Report");
_("TB Specimen Manifest");
