<?php

// SYSTEM GENERATED FILE. DO NOT EDIT.

// THIS FILE IS USED TO GENERATE THE STRING TRANSLATIONS.

_("DASHBOARD");
_("ADMIN");
_("Access Control");
_("Roles");
_("Users");
_("Facilities");
_("Monitoring");
_("System Configuration");
_("Other Lab Tests Config");
_("VL Config");
_("EID Config");
_("Covid-19 Config");
_("Hepatitis Config");
_("TB Config");
_("User Activity Log");
_("Audit Trail");
_("API History");
_("Source of Requests");
_("General Configuration");
_("Instruments");
_("Geographical Divisions");
_("Implementation Partners");
_("Funding Sources");
_("Sample Types");
_("Testing Reasons");
_("Test Failure Reasons");
_("Symptoms");
_("Sample Rejection Reasons");
_("Test Result Units");
_("Test Methods");
_("Test Categories");
_("Test Type Configuration");
_("ART Regimen");
_("Rejection Reasons");
_("Sample Type");
_("Results");
_("Test Reasons");
_("Co-morbidities");
_("QC Test Kits");
_("Risk Factors");
_("OTHER LAB TESTS");
_("Request Management");
_("Test Result Management");
_("Management");
_("HIV VIRAL LOAD");
_("EARLY INFANT DIAGNOSIS (EID)");
_("COVID-19");
_("HEPATITIS");
_("TUBERCULOSIS");
_("View Test Requests");
_("Add New Request");
_("Add Samples from Manifest");
_("Manage Batch");
_("Lab Test Manifest");
_("Enter Result Manually");
_("Failed/Hold Samples");
_("Manage Results Status");
_("Sample Status Report");
_("Export Results");
_("Print Result");
_("Sample Rejection Report");
_("VL Manifest");
_("Import Result From File");
_("Control Report");
_("Clinic Reports");
_("VL Lab Weekly Report");
_("Sample Monitoring Report");
_("VL Testing Target Report");
_("EID Manifest");
_("Clinic Report");
_("EID Testing Target Report");
_("Covid-19 Manifest");
_("Confirmation Manifest");
_("Record Confirmatory Tests");
_("Covid-19 QC Data");
_("COVID-19 Testing Target Report");
_("Hepatitis Manifest");
_("Hepatitis Testing Target Report");
_("TB Manifest");
_("Hold");
_("Lost");
_("Sample Reordered");
_("Rejected");
_("Failed/Invalid");
_("Sample Registered at Testing Lab");
_("Accepted");
_("Awaiting Approval");
_("Sample Registered at Health Center");
_("Sample Expired");
_("No Result");
_("Access");
_("Add");
_("Edit");
_("View");
_("Print Result PDF");
_("Export VL Data");
_("Email Test Request");
_("Manage VL Result Status (Approve/Reject)");
_("High VL Report");
_("Contact Notes (High VL Reports)");
_("Dashboard");
_("Email Test Result");
_("VL Weekly Report");
_("Controls Report");
_("Add Facility Map");
_("Access Facility Map");
_("Edit Facility Map");
_("Export VL Data in Excel");
_("View Batches");
_("Add Batch");
_("Edit Batch");
_("Import Result File");
_("Manage Result Status");
_("Print Results");
_("Export Data");
_("Record Final Result");
_("Can Record Confirmatory Tests");
_("Update Record Confirmatory Tests");
_("Covid-19 Confirmation Manifest");
_("Add New Confirmation Manifest");
_("Generate Positive Confirmation Manifest");
_("Edit Positive Confirmation Manifest");
_("EID Clinic Reports");
_("Covid-19 Clinic Reports");
_("Manage Reference");
_("Manage Comorbidities");
_("Add Comorbidities");
_("Edit Comorbidities");
_("Manage Sample Rejection Reasons");
_("Add Sample Rejection Reason");
_("Edit Sample Rejection Reason");
_("Manage VL Reference Tables");
_("Manage EID Reference Tables");
_("Manage Common Reference Tables");
_("Edit Locked VL Samples");
_("Edit Locked EID Samples");
_("Edit Locked Covid-19 Samples");
_("Monthly Threshold Report");
_("Manage Hepatitis Reference");
_("Suppressed Target report");
_("Hepatitis Clinic Reports");
_("Hepatitis Testing Target Reports");
_("Hepatitis Sample Rejection Reports");
_("Hepatitis Sample Status Reports");
_("DHIS2");
_("Manage Geographical Divisions");
_("Add Geographical Divisions");
_("Edit Geographical Divisions");
_("Sync History");
_("Hepatitis Export");
_("Add Move Samples");
_("TB Clinic Report");
_("Export VL Requests");
_("Export EID Requests");
_("Export Covid-19 Requests ");
_("Export Hepatitis Requests");
_("Export TB Requests");
_("API Sync History");
_("Sources of Requests Report");
_("Add Covid-19 QC Data");
_("Edit Covid-19 QC Data");
_("Manage VL Reference");
_("Manage VL Results");
_("Sync Status");
_("Edit Test Type");
_("View Generic Tests");
_("Add Generic Tests");
_("Add Samples From Manifest");
_("Specimen Referral Manifest List");
_("Edit Generic Tests");
_("Manage Test Results");
_("Manage Failed Results");
_("Approve Test Results");
_("Export Report in Excel");
_("Export Report in PDF");
_("Add VL Result Types");
_("Edit VL Result Types");
_("Import Result from Files");
_("View VL Manifests");
_("View EID Manifests");
_("View COVID-19 Manifests");
_("View Hepatitis Manifests");
_("View TB Manifests");
_("View Lab Tests Manifests");
_("Add VL Manifests");
_("Add EID Manifests");
_("Add COVID-19 Manifests");
_("Add Hepatitis Manifests");
_("Add TB Manifests");
_("Add Lab Tests Manifests");
_("Edit VL Manifests");
_("Edit EID Manifests");
_("Edit COVID-19 Manifests");
_("Edit Hepatitis Manifests");
_("Edit TB Manifests");
_("Edit Lab Tests Manifests");
_("Add New Batch");
_("Add/Edit Test Types");
_("Manage Sample Types");
_("Manage Testing Reasons");
_("Manage Symptoms");
_("Manage Test Failure Reasons");
_("Manage Test Result Units");
_("Manage Test Methods");
_("Manage Test Categories");
_("Edit Locked Samples");
_("Export Requests");
_("Common Reference Tables");
_("Covid-19 Batch Management");
_("Covid-19 Reports");
_("Covid-19 Reference Tables");
_("Covid-19 Request Management");
_("Covid-19 Result Management");
_("EID Batch Management");
_("EID Reports");
_("EID Reference Management");
_("EID Request Management");
_("EID Result Management");
_("Manage Facility");
_("Lab Tests Report Management");
_("Lab Tests Request Management");
_("Lab Tests Result Management");
_("Lab Tests Batch Management");
_("Configure Generic Tests");
_("Manage General Config");
_("Hepatitis Batch Management");
_("Hepatitis Reports");
_("Hepatitis Reference Management");
_("Hepatitis Request Management");
_("Hepatitis Results Management");
_("Import Results using file Import");
_("Manage Instruments");
_("Move Samples");
_("Manage Roles");
_("TB Batch Management");
_("TB Reports");
_("TB Reference");
_("TB Request Management");
_("TB Result Management");
_("Manage Test Request Email Config");
_("Manage Test Result Email Config");
_("Manage Test Type");
_("Manage Users");
_("Manage VL Batch");
_("VL Reference Management");
_("VL Reports");
_("VL Requests");
_("VL Results");
