<?php

// SYSTEM GENERATED FILE. DO NOT EDIT.

// THIS FILE IS USED TO GENERATE THE STRING TRANSLATIONS.

_translate("DASHBOARD");
_translate("ADMIN");
_translate("Access Control");
_translate("Roles");
_translate("Users");
_translate("Facilities");
_translate("Monitoring");
_translate("System Configuration");
_translate("Other Lab Tests Config");
_translate("VL Config");
_translate("EID Config");
_translate("Covid-19 Config");
_translate("Hepatitis Config");
_translate("TB Config");
_translate("User Activity Log");
_translate("Audit Trail");
_translate("API History");
_translate("Source of Requests");
_translate("General Configuration");
_translate("Instruments");
_translate("Geographical Divisions");
_translate("Implementation Partners");
_translate("Funding Sources");
_translate("Sample Types");
_translate("Testing Reasons");
_translate("Test Failure Reasons");
_translate("Symptoms");
_translate("Sample Rejection Reasons");
_translate("Test Result Units");
_translate("Test Methods");
_translate("Test Categories");
_translate("Test Type Configuration");
_translate("ART Regimen");
_translate("Rejection Reasons");
_translate("Sample Type");
_translate("Results");
_translate("Test Reasons");
_translate("Co-morbidities");
_translate("QC Test Kits");
_translate("Risk Factors");
_translate("OTHER LAB TESTS");
_translate("Request Management");
_translate("Test Result Management");
_translate("Management");
_translate("HIV VIRAL LOAD");
_translate("EARLY INFANT DIAGNOSIS (EID)");
_translate("COVID-19");
_translate("HEPATITIS");
_translate("TUBERCULOSIS");
_translate("View Test Requests");
_translate("Add New Request");
_translate("Add Samples from Manifest");
_translate("Manage Batch");
_translate("Lab Test Manifest");
_translate("Enter Result Manually");
_translate("Failed/Hold Samples");
_translate("Manage Results Status");
_translate("Sample Status Report");
_translate("Export Results");
_translate("Print Result");
_translate("Sample Rejection Report");
_translate("VL Manifest");
_translate("Import Results From File");
_translate("Control Report");
_translate("Clinic Reports");
_translate("VL Lab Weekly Report");
_translate("Sample Monitoring Report");
_translate("VL Testing Target Report");
_translate("EID Manifest");
_translate("Clinic Report");
_translate("EID Testing Target Report");
_translate("Covid-19 Manifest");
_translate("Confirmation Manifest");
_translate("Record Confirmatory Tests");
_translate("Covid-19 QC Data");
_translate("COVID-19 Testing Target Report");
_translate("Hepatitis Manifest");
_translate("Hepatitis Testing Target Report");
_translate("TB Manifest");
_translate("Lab Sync Status");
_translate("Recommended Corrective Actions");
_translate("Send Result Mail");
_translate("E-mail Test Result");
_translate("Lab Storage");
_translate("CLUSTERS OF DIFFERENTIATION 4");
_translate("View Test Request");
_translate("CD4 Manifest");
_translate("CD4 Config");
_translate("Hold");
_translate("Lost");
_translate("Sample Reordered");
_translate("Rejected");
_translate("Failed/Invalid");
_translate("Sample Registered at Testing Lab");
_translate("Accepted");
_translate("Awaiting Approval");
_translate("Sample Registered at Health Center");
_translate("Expired");
_translate("No Result");
_translate("Cancelled");
_translate("Access");
_translate("Add");
_translate("Edit");
_translate("View");
_translate("Print Result PDF");
_translate("Export VL Data");
_translate("Manage VL Result Status (Approve/Reject)");
_translate("High VL Report");
_translate("Contact Notes (High VL Reports)");
_translate("Dashboard");
_translate("VL Weekly Report");
_translate("Controls Report");
_translate("Add Facility Map");
_translate("Edit Facility Map");
_translate("Export VL Data in Excel");
_translate("View Batches");
_translate("Add Batch");
_translate("Edit Batch");
_translate("Manage Result Status");
_translate("Print Results");
_translate("Export Data");
_translate("Record Final Result");
_translate("Can Record Confirmatory Tests");
_translate("Update Record Confirmatory Tests");
_translate("Covid-19 Confirmation Manifest");
_translate("Add New Confirmation Manifest");
_translate("Generate Positive Confirmation Manifest");
_translate("Edit Positive Confirmation Manifest");
_translate("EID Clinic Reports");
_translate("Covid-19 Clinic Reports");
_translate("Manage Reference");
_translate("Manage Comorbidities");
_translate("Add Comorbidities");
_translate("Edit Comorbidities");
_translate("Manage Sample Rejection Reasons");
_translate("Add Sample Rejection Reason");
_translate("Edit Sample Rejection Reason");
_translate("Manage VL Reference Tables");
_translate("Manage EID Reference Tables");
_translate("Edit Locked VL Samples");
_translate("Edit Locked EID Samples");
_translate("Edit Locked Covid-19 Samples");
_translate("Monthly Threshold Report");
_translate("Manage Hepatitis Reference");
_translate("Suppressed Target report");
_translate("Hepatitis Clinic Reports");
_translate("Hepatitis Testing Target Reports");
_translate("Hepatitis Sample Rejection Reports");
_translate("Hepatitis Sample Status Reports");
_translate("DHIS2");
_translate("Covid-19 Sync Request");
_translate("Manage Geographical Divisions");
_translate("Add Geographical Divisions");
_translate("Edit Geographical Divisions");
_translate("Sync History");
_translate("Hepatitis Export");
_translate("Add Move Samples");
_translate("TB Clinic Report");
_translate("Export VL Requests");
_translate("Export EID Requests");
_translate("Export Covid-19 Requests ");
_translate("Export Hepatitis Requests");
_translate("Export TB Requests");
_translate("API Sync History");
_translate("Sources of Requests Report");
_translate("Add Covid-19 QC Data");
_translate("Edit Covid-19 QC Data");
_translate("Manage VL Results");
_translate("Sync Status");
_translate("Edit Test Type");
_translate("Add VL Result Types");
_translate("Edit VL Result Types");
_translate("Export Report in Excel");
_translate("Export Report in PDF");
_translate("View Generic Tests");
_translate("Add Generic Tests");
_translate("Add Batch Code");
_translate("Edit Generic Tests");
_translate("Manage Test Results");
_translate("Manage Failed Results");
_translate("Approve Test Results");
_translate("Add New Batch");
_translate("Import VL Results from Files");
_translate("Import EID Results from Files");
_translate("Import COVID-19 Results from Files");
_translate("Import Hepatitis Results from Files");
_translate("Import TB Results from Files");
_translate("Import Results from Files");
_translate("View VL Manifests");
_translate("View EID Manifests");
_translate("View COVID-19 Manifests");
_translate("View Hepatitis Manifests");
_translate("View TB Manifests");
_translate("View Lab Tests Manifests");
_translate("Add VL Manifests");
_translate("Add EID Manifests");
_translate("Add COVID-19 Manifests");
_translate("Add Hepatitis Manifests");
_translate("Add TB Manifests");
_translate("Add Lab Tests Manifests");
_translate("Edit VL Manifests");
_translate("Edit EID Manifests");
_translate("Edit COVID-19 Manifests");
_translate("Edit Hepatitis Manifests");
_translate("Edit TB Manifests");
_translate("Edit Lab Tests Manifests");
_translate("Move VL Manifests");
_translate("Move EID Manifests");
_translate("Move COVID-19 Manifests");
_translate("Move Hepatitis Manifests");
_translate("Move TB Manifests");
_translate("Move Lab Tests Manifests");
_translate("Add/Edit Test Types");
_translate("Manage Sample Types");
_translate("Manage Testing Reasons");
_translate("Manage Symptoms");
_translate("Manage Test Failure Reasons");
_translate("Manage Test Result Units");
_translate("Manage Test Methods");
_translate("Manage Test Categories");
_translate("Edit Locked Samples");
_translate("Export Requests");
_translate("Clone Generic Tests");
_translate("Manage Patients");
_translate("Add Patient");
_translate("Edit Patient");
_translate("Edit Locked Generic Tests Samples");
_translate("Email Test Result");
_translate("Export CD4 Requests");
_translate("Add CD4 Manifests");
_translate("Edit CD4 Manifests");
_translate("View CD4 Manifests");
_translate("Edit Batches");
_translate("Email Test Results");
_translate("Import Results from Files");
_translate("CD4 Clinic Reports");
_translate("Manage CD4 Reference Tables");
_translate("Add Lab Storage");
_translate("Edit Lab Storage");
_translate("Manage Lab Storage");
_translate("CD4 Batch Management");
_translate("CD4 Reports");
_translate("CD4 Reference Management");
_translate("CD4 Requests");
_translate("CD4 Results");
_translate("Common Reference Tables");
_translate("Covid-19 Batch Management");
_translate("Covid-19 Reports");
_translate("Covid-19 Reference Tables");
_translate("Covid-19 Request Management");
_translate("Covid-19 Result Management");
_translate("EID Batch Management");
_translate("EID Reports");
_translate("EID Reference Management");
_translate("EID Request Management");
_translate("EID Result Management");
_translate("Manage Facility");
_translate("Lab Tests Report Management");
_translate("Lab Tests Request Management");
_translate("Lab Tests Result Management");
_translate("Lab Tests Batch Management");
_translate("Configure Generic Lab Tests");
_translate("Manage General Config");
_translate("Hepatitis Batch Management");
_translate("Hepatitis Reports");
_translate("Hepatitis Reference Management");
_translate("Hepatitis Request Management");
_translate("Hepatitis Results Management");
_translate("Manage Instruments");
_translate("Move Samples");
_translate("Manage Roles");
_translate("TB Batch Management");
_translate("TB Reports");
_translate("TB Reference");
_translate("TB Request Management");
_translate("TB Result Management");
_translate("Manage Test Request Email Config");
_translate("Manage Test Result Email Config");
_translate("Manage Test Type");
_translate("Manage Users");
_translate("Manage VL Batch");
_translate("VL Reference Management");
_translate("VL Reports");
_translate("VL Requests");
_translate("VL Results");
