<?php

// DO NOT MODIFY THIS FILE
// Version is defined in app/system/constants.php
// This file is automatically generated by the build process
defined('VERSION')
    || define('VERSION', '5.2.9.7822');
