CREATE TABLE `audit_vl_request_form` (
 `vl_sample_id` int(11) NOT NULL,
 `vlsm_instance_id` varchar(255) NOT NULL,
 `vlsm_country_id` int(11) NOT NULL DEFAULT '1',
 `remote_sample_code` varchar(255) DEFAULT NULL,
 `serial_no` varchar(255) DEFAULT NULL,
 `facility_id` int(11) DEFAULT NULL,
 `province_id` varchar(255) DEFAULT NULL,
 `facility_sample_id` varchar(255) DEFAULT NULL,
 `sample_batch_id` varchar(11) DEFAULT NULL,
 `sample_package_id` varchar(11) DEFAULT NULL,
 `sample_package_code` varchar(255) DEFAULT NULL,
 `sample_reordered` varchar(45) NOT NULL DEFAULT 'no',
 `remote_sample_code_key` varchar(255) DEFAULT NULL,
 `remote_sample_code_format` varchar(255) DEFAULT NULL,
 `sample_code_key` varchar(255) DEFAULT NULL,
 `sample_code_format` varchar(255) DEFAULT NULL,
 `sample_code_title` varchar(45) NOT NULL DEFAULT 'auto',
 `sample_code` varchar(255) DEFAULT NULL,
 `test_urgency` varchar(255) DEFAULT NULL,
 `funding_source` int(11) DEFAULT NULL,
 `implementing_partner` int(11) DEFAULT NULL,
 `patient_first_name` varchar(255) DEFAULT NULL,
 `patient_middle_name` varchar(255) DEFAULT NULL,
 `patient_last_name` varchar(255) DEFAULT NULL,
 `patient_responsible_person` varchar(255) DEFAULT NULL,
 `patient_nationality` int(11) DEFAULT NULL,
 `patient_province` varchar(255) DEFAULT NULL,
 `patient_district` varchar(255) DEFAULT NULL,
 `patient_group` varchar(255) DEFAULT NULL,
 `patient_art_no` varchar(255) DEFAULT NULL,
 `patient_dob` date DEFAULT NULL,
 `patient_gender` varchar(255) DEFAULT NULL,
 `patient_mobile_number` varchar(255) DEFAULT NULL,
 `patient_location` varchar(255) DEFAULT NULL,
 `patient_address` text,
 `patient_art_date` date DEFAULT NULL,
 `patient_receiving_therapy` varchar(255) DEFAULT NULL,
 `patient_drugs_transmission` varchar(255) DEFAULT NULL,
 `patient_tb` varchar(255) DEFAULT NULL,
 `patient_tb_yes` varchar(255) DEFAULT NULL,
 `sample_collection_date` datetime DEFAULT NULL,
 `sample_type` int(11) DEFAULT NULL,
 `is_patient_new` varchar(45) DEFAULT NULL,
 `treatment_initiation` varchar(255) DEFAULT NULL,
 `line_of_treatment` int(11) DEFAULT NULL,
 `line_of_treatment_ref_type` varchar(255) DEFAULT NULL,
 `current_regimen` varchar(255) DEFAULT NULL,
 `date_of_initiation_of_current_regimen` varchar(255) DEFAULT NULL,
 `is_patient_pregnant` varchar(255) DEFAULT NULL,
 `is_patient_breastfeeding` varchar(255) DEFAULT NULL,
 `pregnancy_trimester` int(11) DEFAULT NULL,
 `arv_adherance_percentage` varchar(255) DEFAULT NULL,
 `is_adherance_poor` varchar(255) DEFAULT NULL,
 `consent_to_receive_sms` varchar(45) DEFAULT NULL,
 `number_of_enhanced_sessions` varchar(255) DEFAULT NULL,
 `last_vl_date_routine` date DEFAULT NULL,
 `last_vl_result_routine` varchar(255) DEFAULT NULL,
 `last_vl_sample_type_routine` int(11) DEFAULT NULL,
 `last_vl_date_failure_ac` date DEFAULT NULL,
 `last_vl_result_failure_ac` varchar(255) DEFAULT NULL,
 `last_vl_sample_type_failure_ac` int(11) DEFAULT NULL,
 `last_vl_date_failure` date DEFAULT NULL,
 `last_vl_result_failure` varchar(255) DEFAULT NULL,
 `last_vl_sample_type_failure` int(11) DEFAULT NULL,
 `last_vl_date_ecd` date DEFAULT NULL,
 `last_vl_result_ecd` varchar(255) DEFAULT NULL,
 `last_vl_date_cf` date DEFAULT NULL,
 `last_vl_result_cf` varchar(255) DEFAULT NULL,
 `last_vl_date_if` date DEFAULT NULL,
 `last_vl_result_if` varchar(255) DEFAULT NULL,
 `request_clinician_name` varchar(255) DEFAULT NULL,
 `test_requested_on` date DEFAULT NULL,
 `request_clinician_phone_number` varchar(255) DEFAULT NULL,
 `sample_testing_date` datetime DEFAULT NULL,
 `vl_focal_person` varchar(255) DEFAULT NULL,
 `vl_focal_person_phone_number` varchar(255) DEFAULT NULL,
 `sample_received_at_hub_datetime` datetime DEFAULT NULL,
 `sample_received_at_vl_lab_datetime` datetime DEFAULT NULL,
 `result_dispatched_datetime` datetime DEFAULT NULL,
 `is_sample_rejected` varchar(255) DEFAULT NULL,
 `sample_rejection_facility` int(11) DEFAULT NULL,
 `reason_for_sample_rejection` int(11) DEFAULT NULL,
 `request_created_by` varchar(255) NOT NULL,
 `request_created_datetime` datetime DEFAULT NULL,
 `last_modified_by` varchar(255) DEFAULT NULL,
 `last_modified_datetime` datetime DEFAULT NULL,
 `patient_other_id` varchar(255) DEFAULT NULL,
 `patient_age_in_years` varchar(255) DEFAULT NULL,
 `patient_age_in_months` varchar(255) DEFAULT NULL,
 `treatment_initiated_date` date DEFAULT NULL,
 `patient_anc_no` varchar(255) DEFAULT NULL,
 `treatment_details` text,
 `sample_visit_type` varchar(45) DEFAULT NULL,
 `vl_sample_suspected_treatment_failure_at` varchar(255) DEFAULT NULL,
 `lab_name` varchar(255) DEFAULT NULL,
 `lab_id` int(11) DEFAULT NULL,
 `lab_code` int(11) DEFAULT NULL,
 `lab_technician` varchar(500) DEFAULT NULL,
 `lab_contact_person` varchar(255) DEFAULT NULL,
 `lab_phone_number` varchar(255) DEFAULT NULL,
 `sample_registered_at_lab` datetime DEFAULT NULL,
 `sample_tested_datetime` datetime DEFAULT NULL,
 `result_value_log` varchar(255) DEFAULT NULL,
 `result_value_absolute` varchar(255) DEFAULT NULL,
 `result_value_text` varchar(255) DEFAULT NULL,
 `result_value_absolute_decimal` varchar(255) DEFAULT NULL,
 `result` varchar(255) DEFAULT NULL,
 `approver_comments` text,
 `reason_for_vl_result_changes` text,
 `lot_number` varchar(255) DEFAULT NULL,
 `lot_expiration_date` date DEFAULT NULL,
 `tested_by` varchar(255) DEFAULT NULL,
 `result_approved_by` varchar(255) DEFAULT NULL,
 `result_approved_datetime` datetime DEFAULT NULL,
 `result_reviewed_by` varchar(255) DEFAULT NULL,
 `result_reviewed_datetime` datetime DEFAULT NULL,
 `test_methods` varchar(255) DEFAULT NULL,
 `contact_complete_status` varchar(255) DEFAULT NULL,
 `last_viral_load_date` date DEFAULT NULL,
 `last_viral_load_result` varchar(255) DEFAULT NULL,
 `last_vl_result_in_log` varchar(255) DEFAULT NULL,
 `reason_for_vl_testing` varchar(255) DEFAULT NULL,
 `reason_for_vl_testing_other` varchar(255) DEFAULT NULL,
 `drug_substitution` varchar(255) DEFAULT NULL,
 `sample_collected_by` varchar(255) DEFAULT NULL,
 `facility_comments` text,
 `vl_test_platform` varchar(255) DEFAULT NULL,
 `cphl_vl_result` varchar(255) DEFAULT NULL,
 `import_machine_name` int(11) DEFAULT NULL,
 `facility_support_partner` varchar(255) DEFAULT NULL,
 `has_patient_changed_regimen` varchar(45) DEFAULT NULL,
 `reason_for_regimen_change` varchar(255) DEFAULT NULL,
 `regimen_change_date` date DEFAULT NULL,
 `plasma_conservation_temperature` float DEFAULT NULL,
 `plasma_conservation_duration` varchar(45) DEFAULT NULL,
 `physician_name` varchar(255) DEFAULT NULL,
 `date_test_ordered_by_physician` date DEFAULT NULL,
 `vl_test_number` varchar(45) DEFAULT NULL,
 `date_dispatched_from_clinic_to_lab` datetime DEFAULT NULL,
 `result_printed_datetime` datetime DEFAULT NULL,
 `result_sms_sent_datetime` datetime DEFAULT NULL,
 `is_request_mail_sent` varchar(45) NOT NULL DEFAULT 'no',
 `request_mail_datetime` datetime DEFAULT NULL,
 `is_result_mail_sent` varchar(45) NOT NULL DEFAULT 'no',
 `result_mail_datetime` datetime DEFAULT NULL,
 `is_result_sms_sent` varchar(45) NOT NULL DEFAULT 'no',
 `test_request_export` int(11) NOT NULL DEFAULT '0',
 `test_request_import` int(11) NOT NULL DEFAULT '0',
 `test_result_export` int(11) NOT NULL DEFAULT '0',
 `test_result_import` int(11) NOT NULL DEFAULT '0',
 `request_exported_datetime` datetime DEFAULT NULL,
 `request_imported_datetime` datetime DEFAULT NULL,
 `result_exported_datetime` datetime DEFAULT NULL,
 `result_imported_datetime` datetime DEFAULT NULL,
 `result_status` int(11) NOT NULL,
 `import_machine_file_name` varchar(255) DEFAULT NULL,
 `manual_result_entry` varchar(255) DEFAULT NULL,
 `consultation` varchar(255) DEFAULT NULL,
 `first_line` varchar(255) DEFAULT NULL,
 `second_line` varchar(255) DEFAULT NULL,
 `first_viral_load` varchar(255) DEFAULT NULL,
 `collection_type` varchar(255) DEFAULT NULL,
 `sample_processed` varchar(255) DEFAULT NULL,
 `vl_result_category` varchar(255) DEFAULT NULL,
 `vldash_sync` int(11) NOT NULL DEFAULT '0',
 `source` varchar(500) DEFAULT 'manual',
 `ward` varchar(255) DEFAULT NULL,
 `art_cd_cells` varchar(255) DEFAULT NULL,
 `art_cd_date` date DEFAULT NULL,
 `who_clinical_stage` varchar(255) DEFAULT NULL,
 `reason_testing_png` text,
 `tech_name_png` varchar(255) DEFAULT NULL,
 `qc_tech_name` varchar(255) DEFAULT NULL,
 `qc_tech_sign` varchar(255) DEFAULT NULL,
 `qc_date` varchar(255) DEFAULT NULL,
 `whole_blood_ml` varchar(50) DEFAULT NULL,
 `whole_blood_vial` varchar(50) DEFAULT NULL,
 `plasma_ml` varchar(50) DEFAULT NULL,
 `plasma_vial` varchar(50) DEFAULT NULL,
 `plasma_process_time` varchar(255) DEFAULT NULL,
 `plasma_process_tech` varchar(255) DEFAULT NULL,
 `batch_quality` varchar(255) DEFAULT NULL,
 `sample_test_quality` varchar(255) DEFAULT NULL,
 `repeat_sample_collection` varchar(45) DEFAULT NULL,
 `failed_test_date` datetime DEFAULT NULL,
 `failed_test_tech` varchar(255) DEFAULT NULL,
 `failed_vl_result` varchar(255) DEFAULT NULL,
 `failed_batch_quality` varchar(255) DEFAULT NULL,
 `failed_sample_test_quality` varchar(255) DEFAULT NULL,
 `failed_batch_id` varchar(255) DEFAULT NULL,
 `clinic_date` date DEFAULT NULL,
 `report_date` date DEFAULT NULL,
 `sample_to_transport` varchar(255) DEFAULT NULL,
 `requesting_professional_number` varchar(255) DEFAULT NULL,
 `requesting_category` varchar(255) DEFAULT NULL,
 `requesting_vl_service_sector` varchar(255) DEFAULT NULL,
 `requesting_facility_id` int(11) DEFAULT NULL,
 `requesting_person` varchar(255) DEFAULT NULL,
 `requesting_phone` varchar(255) DEFAULT NULL,
 `requesting_date` date DEFAULT NULL,
 `collection_site` varchar(255) DEFAULT NULL,
 `data_sync` varchar(10) NOT NULL DEFAULT '0',
 `remote_sample` varchar(255) NOT NULL DEFAULT 'no',
 `recency_vl` varchar(255) NOT NULL DEFAULT 'no',
 `recency_sync` int(11) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- DROP TRIGGER audit_vl_form;
DELIMITER //
CREATE TRIGGER audit_vl_form AFTER UPDATE ON vl_request_form
FOR EACH ROW BEGIN  
    INSERT INTO audit_vl_request_form select * from vl_request_form where vl_sample_id = NEW.vl_sample_id;
END;//
DELIMITER ;